development:
  adapter: async

test:
  adapter: async

production:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "async" %>
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: cargaclick_production
  allowed_request_origins:
    - https://www.cargaclick.com.br
    - https://cargaclick.onrender.com
